Default: &defaults
  database: haskellcurry.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: haskellcurry_test.sqlite3
  <<: *defaults

Staging:
  database: haskellcurry_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: haskellcurry_production.sqlite3
  poolsize: 100
  <<: *defaults
